server:
  port: 8008

spring:
  application:
    name: message-service
  profiles:
    active: dev   # 以后切环境只这里
  config:
    import:
      - optional:nacos:message-service-${spring.profiles.active}.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ""
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: ""
        group: DEFAULT_GROUP
        import-check:
          enabled: false
