server:
  port: 8012

spring:
  application:
    name: search-service
  profiles:
    active: dev   # 以后切环境只改这里
  config:
    import:
      - optional:nacos:search-service-${spring.profiles.active}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ""
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: ""
        group: DEFAULT_GROUP
        import-check:
          enabled: false
