server:
  port: 8012

spring:
  application:
    name: search-service
  config:
    import:
      - optional:nacos:application-${spring.profiles.active:}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        import-check:
          enabled: false

  data:
    redis:
      host: localhost
      port: 6379
      password: xiaojie666
      database: 2
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  elasticsearch:
    uris: http://localhost:9200

# JWT
jwt:
  secret: OnlyStudentsSecretKey2024
  expiration: 86400000
