server:
  port: 8001
  tomcat:
    threads:
      max: 500
      min-spare: 50
    max-connections: 10000
    accept-count: 1000
    connection-timeout: 20000

spring:
  application:
    name: user-service
  profiles:
    active: dev   # 以后切环境只改这里
  config:
    import:
      - optional:nacos:user-service-${spring.profiles.active}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ""
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: ""
        group: DEFAULT_GROUP
        import-check:
          enabled: false